version: '3.8'

networks:
  mindease_network:
services:
  db:
    image: postgres:latest
    container_name: mindease-db-1
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script
    ports:
      - "5432:5432"
    networks:
      - mindease_network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: ./backend
    container_name: dms_server
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    volumes:
      - ./logs:/app/logs
    networks:
      - mindease_network

    depends_on:
      db:
        condition: service_healthy

  #TODO: Frontend needs still fixing
#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "5173:5173"
#    volumes:
#      - ./frontend:/app
#    working_dir: /app
#    command: [ "npm", "start" ]
#    depends_on:
#      - app

volumes:
  db_data: